dirs:
  - .
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 429

httpHeaders:
  - url:
      - https://medium.com/
    headers:
      User-Agent: 'Mozilla/5.0 (X11; Linux x86_64)'
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      Accept-Language: 'en-US,en;q=0.5'

  - url:
      - https://www.npmjs.com/
    headers:
      User-Agent: 'Mozilla/5.0 (X11; Linux x86_64)'
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      Accept-Language: 'en-US,en;q=0.5'

ignorePatterns:
  - pattern: '^https://medium\.com/.*$'
