name: 'Check Action IDs'
inputs:
  network-name:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      uses: ./.github/actions/setup
    - name: Prepare Config
      run: yarn ci:prepare-config
      shell: bash
    - name: Check Action IDs
      run: yarn check-network-action-ids ${{ inputs.network-name }}
      shell: bash
